[package]
name = "font-subset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
write-fonts = { path = "../write-fonts",version = "*" }
read-fonts = { path = "../read-fonts",version = "*" }